# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pack' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pack
  pod 'Amplitude-iOS', '~> 3.14.1'

  target 'Pack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
